### ISSUE TITLE
Show company image

### ISSUE THREAD

**Issue by keulinho** [shopwareLabs/product-import-app#40]
after https://github.com/shopware/portal/pull/108 companies can have images, we should show the first image in the drawer

**Comment by JanPietrzyk** [comment]
I'm curently adding a cover field for that

**Comment by JanPietrzyk** [comment]
oh, and we call it *merchant* ;)

**Comment by keulinho** [comment]
@JanPietrzyk  can you link an issue/PR here if one exists? ;)

**Comment by HoelShare** [comment]
Currently it's impossible to upload an image https://github.com/shopwareDowntown/portal/issues/209
